# netlify.toml

[build]
  base = ""               # جذر المشروع
  publish = "build"       # مجلد البناء الناتج عن CRACO
  command = "npm run build"  # أمر البناء

[[redirects]]
  from = "/*"             # كل الطلبات
  to = "/index.html"      # يعيد توجيهها إلى index.html
  status = 200            # حالة الاستجابة
